image: node:10

stages:
  - test_backend

cache:
  paths:
  - node_modules/
  - client/node_modules

test_backend:
  stage: test
  services:
    - mongo:4
  script:
    - npm i npm@latest -g
    - npm i
    - npm test
